## Dev tool: (re)generates a locale file containing EVERY translatable string
## in the game, so a translator's checklist can't drift from what the game
## actually contains — same guarantee, and same preserve-existing-work
## behaviour, as tests/gen_art_manifest.gd.
##
##   godot --headless --path godot -s tests/gen_locale_template.gd -- fr
##
## Existing translations are preserved; only new keys are added, and keys
## whose English source has CHANGED since the translation was written are
## reported so a stale translation can't quietly survive a rewrite of the
## original line.
##
## Writes data/base/locale/<lang>.json. The English source for every key is
## kept alongside in a parallel "_source" block, so a translator can work in
## the file itself without cross-referencing the data files.
extends SceneTree

var content: Node
var art: Node


func _initialize() -> void:
	content = root.get_node("Content")
	art = root.get_node("Art")
	await process_frame
	content.reload()
	art.reload()

	var args := OS.get_cmdline_user_args()
	var lang := args[0] if args.size() > 0 else "fr"
	if lang == "en":
		printerr("'en' is the source language — the .gd literals and base JSON are already English; no locale file needed.")
		quit(1)
		return

	var path := "res://data/base/locale/%s.json" % lang
	var existing := _load_existing(path)
	var prev_source: Dictionary = existing.get("_source", {})
	var prev_strings: Dictionary = existing.get("locale_" + lang, {})

	var source := _collect_sources()

	var out_strings := {}
	var added: Array[String] = []
	var stale: Array[String] = []
	for key in source:
		var eng: String = source[key]
		var had: String = str(prev_strings.get(key, ""))
		out_strings[key] = had
		if not prev_strings.has(key):
			added.append(key)
		elif had != "" and prev_source.has(key) and str(prev_source[key]) != eng:
			stale.append(key)

	var dropped: Array = prev_strings.keys().filter(func(k): return not source.has(k))

	var doc := {
		"_comment": "GENERATED by tests/gen_locale_template.gd — re-run it after adding or changing any UI string or content record; existing translations are preserved. Fill in the values under \"locale_%s\"; an empty string means untranslated and the game falls back to the English in \"_source\". See docs/LOCALIZATION.md." % lang,
		"_source": source,
		"locale_" + lang: out_strings,
	}
	DirAccess.make_dir_recursive_absolute("res://data/base/locale")
	var f := FileAccess.open(path, FileAccess.WRITE)
	f.store_string(JSON.stringify(doc, "  ") + "\n")
	f.close()

	var done := 0
	for k in out_strings:
		if str(out_strings[k]) != "":
			done += 1
	print("wrote %s — %d keys, %d translated (%d%%)" % [path, out_strings.size(), done, 0 if out_strings.is_empty() else round(100.0 * done / out_strings.size())])
	if not added.is_empty():
		print("  +%d new key(s)" % added.size())
	if not stale.is_empty():
		printerr("  %d translation(s) whose English source CHANGED — review these: %s" % [stale.size(), ", ".join(stale.slice(0, 10))])
	if not dropped.is_empty():
		printerr("  %d key(s) no longer exist and were dropped: %s" % [dropped.size(), ", ".join(dropped.slice(0, 10))])
	quit(0)


## Every translatable string in the game, keyed the way I18n looks them up.
func _collect_sources() -> Dictionary:
	var src := {}

	# 1. UI chrome. The English source doubles as the key (see I18n.t), so
	#    this list is what the .gd files pass to I18n.t(). It's enumerated
	#    here rather than scraped from source, because a reliable scraper for
	#    GDScript string literals is a bigger thing than this needs — keep it
	#    in step by adding a line whenever you add a t() call.
	for s in _ui_strings():
		src["ui/" + s] = s

	# 2. Content, addressed by the same slug ids the art manifest uses.
	for pool in ["cards_basics", "cards_chroma", "cards_minor", "cards_arcana"]:
		for c in content.registries.get(pool, []):
			var id: String = art.card_id(c)
			_put(src, id + "/n", c.get("n", ""))
			_put(src, id + "/fl", c.get("fl", ""))
	for r in content.readers:
		var rid: String = art.reader_id(r)
		_put(src, rid + "/name", r.get("name", ""))
		_put(src, rid + "/sign", r.get("sign", ""))
		_put(src, rid + "/line", r.get("line", ""))
		_put(src, rid + "/rule", r.get("rule", ""))
	for s in content.sitters:
		_put_sitter(src, art.sitter_id(s), s)
	if not content.boss.is_empty():
		_put_sitter(src, art.sitter_id(content.boss), content.boss)
	for sg in content.signs:
		var sid: String = "sign/" + str(sg.get("k", ""))
		_put(src, sid + "/n", sg.get("n", ""))
		_put(src, sid + "/dn", sg.get("dn", ""))
		_put(src, sid + "/rule", sg.get("rule", ""))
	for role in content.jobs:
		_put(src, "job/" + art.slug(role) + "/t", content.jobs[role].get("t", ""))
		_put(src, "job/" + art.slug(role) + "/role", role)
	for el in content.elements:
		var e: Dictionary = content.elements[el]
		_put(src, "element/" + el + "/label", e.get("label", ""))
		_put(src, "element/" + el + "/gives", e.get("gives", ""))
		_put(src, "element/" + el + "/body", e.get("body", ""))
	for m in content.marks + content.relics:
		_put(src, "mark/" + art.slug(str(m.get("n", ""))) + "/n", m.get("n", ""))
		_put(src, "mark/" + art.slug(str(m.get("n", ""))) + "/text", m.get("text", ""))
	for ev in content.events:
		var eid: String = "event/" + art.slug(str(ev.get("title", "")))
		_put(src, eid + "/title", ev.get("title", ""))
		_put(src, eid + "/body", ev.get("body", ""))
		_put(src, eid + "/head", ev.get("head", ""))
		_put(src, eid + "/line", ev.get("line", ""))
		var oi := 0
		for opt in ev.get("opts", []):
			_put(src, "%s/opt%d/kind" % [eid, oi], opt.get("kind", ""))
			_put(src, "%s/opt%d/name" % [eid, oi], opt.get("name", ""))
			_put(src, "%s/opt%d/text" % [eid, oi], opt.get("text", ""))
			oi += 1
	for tw in content.elite_twists:
		var tid: String = "twist/" + art.slug(str(tw.get("tag", "")))
		_put(src, tid + "/tag", tw.get("tag", ""))
		_put(src, tid + "/t", tw.get("t", ""))
	if not content.shop.is_empty():
		for k in ["title", "body", "head", "line", "burn_name", "burn_text"]:
			_put(src, "shop/" + k, content.shop.get(k, ""))
	return src


func _put_sitter(src: Dictionary, id: String, s: Dictionary) -> void:
	_put(src, id + "/name", s.get("name", ""))
	_put(src, id + "/role", s.get("role", ""))
	_put(src, id + "/brings", s.get("brings", ""))
	_put(src, id + "/win", s.get("win", ""))
	_put(src, id + "/fail", s.get("fail", ""))


func _put(src: Dictionary, key: String, value) -> void:
	var s := str(value).strip_edges()
	if s != "":
		src[key] = s


## Keep in step with the I18n.t() calls in scenes/*.gd.
func _ui_strings() -> Array[String]:
	return [
		# main menu
		"PARLOUR", "BEGIN A READING", "LIBRARY", "SETTINGS", "QUIT",
		"a fortune-teller's ledger, in card form",
		# settings
		"DISPLAY", "Fullscreen", "Toggle between windowed and fullscreen.",
		"Interface scale", "Scales the whole interface. Useful on very large or very small displays.",
		"SOUND", "Master volume", "Mute", "Silence everything.",
		"MOTION", "Animation speed", "off",
		"GAMEPLAY", "Energy per reading", "Hand size",
		"CONTENT", "Load example mods",
		"LANGUAGE", "Language",
		"BACK", "RESET TO DEFAULTS",
		# library
		"All pools", "All elements", "Search by name…",
		"Basics", "Chromatic", "Minor", "Arcana",
		"Pick a card on the left to edit it.", "Nothing matches those filters.",
		"READS AS", "CORE", "EFFECTS", "FLAGS",
		"Energy cost", "Base restore", "Element", "None",
		"REVERT THIS CARD", "REVERT ALL CARDS",
		"Set a value to 0 to remove that effect from the card entirely.",
		# run screens
		"CHOOSE YOUR SIGN", "Every reader is a sign, an element, and a starting deck of ten.",
		"Starts with:", "Who knocks tonight?", "NIGHT", "KNOCK",
		"YOUR HAND — hover a card for its full text", "SAID SO FAR", "(nothing yet)",
		"READ IT", "Composure", "Energy", "Reading", "Denial wall", "Discarded:",
		"BEGIN AGAIN", "sign", "cost", "composure", "denial", "readings",
		"THE APOTHECARY", "ELITE", "THE MAYOR", "ONCE", "PIERCE", "No element",
		# run header + overlays
		"Faith", "Centimes", "Mended", "DECK", "MARKS", "CLOSE",
		"YOUR DECK", "YOUR HANDS", "cards",
		"Nothing on your hands yet. Rings and marks come from elites, events and the apothecary.",
	]


func _load_existing(path: String) -> Dictionary:
	if not FileAccess.file_exists(path):
		return {}
	var f := FileAccess.open(path, FileAccess.READ)
	var parsed = JSON.parse_string(f.get_as_text())
	f.close()
	return parsed if typeof(parsed) == TYPE_DICTIONARY else {}
