## Dev tool: (re)generates a locale file containing EVERY translatable string
## in the game, so a translator's checklist can't drift from what the game
## actually contains — same guarantee, and same preserve-existing-work
## behaviour, as tests/gen_art_manifest.gd.
##
##   godot --headless --path godot -s tests/gen_locale_template.gd -- fr
##
## Existing translations are preserved; only new keys are added, and keys
## whose English source has CHANGED since the translation was written are
## reported so a stale translation can't quietly survive a rewrite of the
## original line.
##
## Writes data/base/locale/<lang>.json. The English source for every key is
## kept alongside in a parallel "_source" block, so a translator can work in
## the file itself without cross-referencing the data files.
extends SceneTree

var content: Node
var art: Node


func _initialize() -> void:
	content = root.get_node("Content")
	art = root.get_node("Art")
	await process_frame
	content.reload()
	art.reload()

	var args := OS.get_cmdline_user_args()
	var lang := args[0] if args.size() > 0 else "fr"
	if lang == "en":
		printerr("'en' is the source language — the .gd literals and base JSON are already English; no locale file needed.")
		quit(1)
		return

	var path := "res://data/base/locale/%s.json" % lang
	var existing := _load_existing(path)
	var prev_source: Dictionary = existing.get("_source", {})
	var prev_strings: Dictionary = existing.get("locale_" + lang, {})

	var source := _collect_sources()

	var out_strings := {}
	var added: Array[String] = []
	var stale: Array[String] = []
	for key in source:
		var eng: String = source[key]
		var had: String = str(prev_strings.get(key, ""))
		out_strings[key] = had
		if not prev_strings.has(key):
			added.append(key)
		elif had != "" and prev_source.has(key) and str(prev_source[key]) != eng:
			stale.append(key)

	var dropped: Array = prev_strings.keys().filter(func(k): return not source.has(k))

	var doc := {
		"_comment": "GENERATED by tests/gen_locale_template.gd — re-run it after adding or changing any UI string or content record; existing translations are preserved. Fill in the values under \"locale_%s\"; an empty string means untranslated and the game falls back to the English in \"_source\". See docs/LOCALIZATION.md." % lang,
		"_source": source,
		"locale_" + lang: out_strings,
	}
	DirAccess.make_dir_recursive_absolute("res://data/base/locale")
	var f := FileAccess.open(path, FileAccess.WRITE)
	f.store_string(JSON.stringify(doc, "  ") + "\n")
	f.close()

	var done := 0
	for k in out_strings:
		if str(out_strings[k]) != "":
			done += 1
	print("wrote %s — %d keys, %d translated (%d%%)" % [path, out_strings.size(), done, 0 if out_strings.is_empty() else round(100.0 * done / out_strings.size())])
	if not added.is_empty():
		print("  +%d new key(s)" % added.size())
	if not stale.is_empty():
		printerr("  %d translation(s) whose English source CHANGED — review these: %s" % [stale.size(), ", ".join(stale.slice(0, 10))])
	if not dropped.is_empty():
		printerr("  %d key(s) no longer exist and were dropped: %s" % [dropped.size(), ", ".join(dropped.slice(0, 10))])
	quit(0)


## Every translatable string in the game, keyed the way I18n looks them up.
func _collect_sources() -> Dictionary:
	var src := {}

	# 1. UI chrome. The English source doubles as the key (see I18n.t), so
	#    this list is what the .gd files pass to I18n.t(). It's enumerated
	#    here rather than scraped from source, because a reliable scraper for
	#    GDScript string literals is a bigger thing than this needs — keep it
	#    in step by adding a line whenever you add a t() call.
	for s in _ui_strings():
		src["ui/" + s] = s

	# 2. Content, addressed by the same slug ids the art manifest uses.
	for pool in ["cards_basics", "cards_chroma", "cards_minor", "cards_arcana"]:
		for c in content.registries.get(pool, []):
			var id: String = art.card_id(c)
			_put(src, id + "/n", c.get("n", ""))
			_put(src, id + "/fl", c.get("fl", ""))
	for r in content.readers:
		var rid: String = art.reader_id(r)
		_put(src, rid + "/name", r.get("name", ""))
		_put(src, rid + "/sign", r.get("sign", ""))
		_put(src, rid + "/line", r.get("line", ""))
		_put(src, rid + "/rule", r.get("rule", ""))
	for s in content.sitters:
		_put_sitter(src, art.sitter_id(s), s)
	if not content.boss.is_empty():
		_put_sitter(src, art.sitter_id(content.boss), content.boss)
	for sg in content.signs:
		var sid: String = "sign/" + str(sg.get("k", ""))
		_put(src, sid + "/n", sg.get("n", ""))
		_put(src, sid + "/dn", sg.get("dn", ""))
		_put(src, sid + "/rule", sg.get("rule", ""))
	# Pronoun words. A locale needs its own set (il/elle/iel and whatever verb
	# agreement it takes) — these are substituted into sign rules at display
	# time by I18n.fill(), so leaving them in English would put English words
	# inside otherwise-translated sentences.
	for pk in content.pronouns:
		var table: Dictionary = content.pronouns[pk]
		for token in table:
			_put(src, "pronoun/" + pk + "/" + token, table[token])
	for role in content.jobs:
		_put(src, "job/" + art.slug(role) + "/t", content.jobs[role].get("t", ""))
		_put(src, "job/" + art.slug(role) + "/role", role)
	for el in content.elements:
		var e: Dictionary = content.elements[el]
		_put(src, "element/" + el + "/label", e.get("label", ""))
		_put(src, "element/" + el + "/gives", e.get("gives", ""))
		_put(src, "element/" + el + "/body", e.get("body", ""))
	for m in content.marks + content.relics:
		_put(src, "mark/" + art.slug(str(m.get("n", ""))) + "/n", m.get("n", ""))
		_put(src, "mark/" + art.slug(str(m.get("n", ""))) + "/text", m.get("text", ""))
	for ev in content.events:
		var eid: String = "event/" + art.slug(str(ev.get("title", "")))
		_put(src, eid + "/title", ev.get("title", ""))
		_put(src, eid + "/body", ev.get("body", ""))
		_put(src, eid + "/head", ev.get("head", ""))
		_put(src, eid + "/line", ev.get("line", ""))
		var oi := 0
		for opt in ev.get("opts", []):
			_put(src, "%s/opt%d/kind" % [eid, oi], opt.get("kind", ""))
			_put(src, "%s/opt%d/name" % [eid, oi], opt.get("name", ""))
			_put(src, "%s/opt%d/text" % [eid, oi], opt.get("text", ""))
			oi += 1
	# Minitel services. The terminal's fixed chrome is deliberately untranslated
	# (see Minitel.gd), but what a SERVICE prints is prose an author wrote, and
	# a mod's terminal may well be set somewhere other than France.
	for code in content.minitel_codes:
		var lines: Array = content.minitel_codes[code].get("screen", [])
		for li in lines.size():
			_put(src, "minitel/%s/screen%d" % [code, li], lines[li])
	for tw in content.elite_twists:
		var tid: String = "twist/" + art.slug(str(tw.get("tag", "")))
		_put(src, tid + "/tag", tw.get("tag", ""))
		_put(src, tid + "/t", tw.get("t", ""))
	if not content.shop.is_empty():
		for k in ["title", "body", "head", "line", "burn_name", "burn_text"]:
			_put(src, "shop/" + k, content.shop.get(k, ""))
	return src


func _put_sitter(src: Dictionary, id: String, s: Dictionary) -> void:
	_put(src, id + "/name", s.get("name", ""))
	_put(src, id + "/role", s.get("role", ""))
	_put(src, id + "/brings", s.get("brings", ""))
	_put(src, id + "/win", s.get("win", ""))
	_put(src, id + "/fail", s.get("fail", ""))


func _put(src: Dictionary, key: String, value) -> void:
	var s := str(value).strip_edges()
	if s != "":
		src[key] = s


## Keep in step with the I18n.t() calls in scenes/*.gd.
func _ui_strings() -> Array[String]:
	return [
		# main menu
		"PARLOUR", "BEGIN A READING", "LIBRARY", "MODS", "SETTINGS", "QUIT",
		"a fortune-teller's ledger, in card form",
		"CONTINUE", "THIS ENDS THE RUN IN PROGRESS — BEGIN ANYWAY", "RESUME ANYWAY",
		"%s card(s) in this run came from content you no longer have and have been removed from the deck.",
		"night %s, knock %s · %s · %s faith",
		"Could not read your saved run.", "content warning(s) — see MODS.",
		"NOTHING IS BEING SAVED — your run, settings and unlocks will all be lost when you close the game. %s",
		"THIS RUN IS NOT BEING SAVED — anything from here is lost if you close the game.",
		# mods screen
		"Packs load in the order below. A later pack wins where two define the same card, sign or reader.",
		"LOADED PACKS", "LOAD MESSAGES", "WHERE TO PUT A MOD", "STEAM WORKSHOP",
		"No packs found at all — even the base game is missing.",
		"priority %s", "%s record(s) in %s",
		"Switched off — nothing from this pack is loaded.",
		"The game's own content. Always loaded, always first.",
		"TURN OFF", "TURN ON", "RELOAD CONTENT",
		"shipped with the game", "bundled example", "your mods folder", "Steam Workshop",
		"Everything loaded cleanly.",
		"%s problem(s). A pack that reports one is still loaded — only the offending record is skipped.",
		"One folder per pack, each with a mod.json. Turn a pack off above rather than deleting it if you only want it gone for a while.",
		"Your own Library changes are pack \"%s\" above — %s card(s).",
		"Connected. Subscribed packs appear in the list above.", "REFRESH SUBSCRIPTIONS",
		"Not connected. Workshop needs a Steam App ID and the GodotSteam extension, neither of which this build has — see docs/STEAM_WORKSHOP.md. Until then, share a pack by sharing its folder.",
		# minitel — the chrome around the machine only. What the terminal itself
		# prints is deliberately untranslated; see Minitel.gd's SAY_* block.
		"MINITEL", "ENVOI",
		"It hums on the sideboard where the telephone used to be. Someone left the bill unpaid and it never stopped working.",
		"You have not dialled anything yet.", "SERVICES YOU HAVE REACHED",
		"Dial 3615 %s",
		# how to play
		"HOW TO PLAY", "THE NIGHT", "ONE READING", "THE WHEEL",
		"WHAT THEY WILL NOT SAY", "THE WORDS ON A CARD", "THE FOUR ELEMENTS",
		"Someone knocks. They have a job, a sign, and something they will not say. Their composure starts at nothing, and you have to fill it before your readings with them run out — then they go home whole.",
		"Eight knocks a night, three nights. The last one on the third night is the mayor, and he is not like the others.",
		"Between knocks you take a road: another sitter, the apothecary, or whatever the evening puts in front of you.",
		"You draw a hand. You lay cards left to right, spending energy, and then you READ IT — they are spoken as one sentence, in the order you laid them.",
		"THE ORDER IS THE WHOLE GAME. Most cards pay attention to what came before them, and a card laid in the wrong place is worth a fraction of the same card laid in the right one.",
		"Energy comes back in full every reading. Your hand does not: whatever is left is discarded and you draw fresh.",
		"The elements run in a ring, and each card's place on it is measured against the card before:",
		"Following the ring forward is a TURN. Saying the same element again is SAME. Going backwards is BACK, and jumping across is a BREAK.",
		"A card that reads \"+4 more if it follows △\" wants the card before it to have carried that element. That is what you are arranging when you decide the order.",
		"A card matching the sitter's own element is always worth a little more.",
		"The elements run in a ring.",
		"Every sitter carries their sign's denial — one named thing it does to every reading you give them. Some of them hold off the first points of anything you say, like a wall; some cut a reading in half; some refuse to hear the same sign twice.",
		"It is written under their name before you start. Read it first: it is usually the difference between a good deck and a good night.",
		"A card that PIERCES ignores denial entirely.",
		"Playable entirely from the keyboard or a gamepad: the arrow keys, Tab or the stick move the highlight, and Confirm activates whatever is lit.",
		"Any of these can be changed in SETTINGS → CONTROLS.",
		"RULES",
		# credits
		"CREDITS", "THE GAME", "BUILT WITH", "ART AND SOUND", "TRANSLATION", "THIS BUILD",
		"Parlour began as a self-contained browser prototype, Parlour v23.dc.html — the design, the writing, the cards and the numbers are all its author's.",
		"This is a port of that prototype to Godot. The rules engine is a direct translation of its simulate(); where the two disagree, the prototype is right.",
		"Design and writing: see the repository.",
		"Godot Engine %s — MIT licence, godotengine.org",
		"The engine's default interface font, Open Sans (Apache 2.0).",
		"Every card face, portrait and sound in this build is a placeholder generated by the project itself, and is meant to be replaced. See docs/ART_GUIDE.md and docs/SOUND_GUIDE.md.",
		"Illustration: unfilled.", "Music and sound: unfilled.",
		"English only.", "Translators: unfilled. See docs/LOCALIZATION.md.",
		"Version %s", "Engine %s", "Content packs loaded: %s",
		# settings — the category rail
		"GAMEPLAY", "VIDEO", "AUDIO", "INTERFACE", "CONTROLS", "LANGUAGE", "CONTENT",
		"RESET THIS SECTION", "RESET EVERYTHING",
		# settings — gameplay
		"Energy per reading", "Hand size",
		"Base energy each reading, before any reader, relic, job or sign modifier. Default 3.",
		"Base cards dealt each reading, before modifiers. Default 5.",
		"These two are the knobs the original prototype exposed. Changing them rebalances the whole game — the defaults (3 and 5) are what everything else is tuned against.",
		# settings — video
		"Window mode", "Windowed", "Borderless", "Fullscreen",
		"Borderless is a window the size of your screen with no frame — it alt-tabs faster than exclusive fullscreen.",
		"Window size", "Sizes larger than your screen are not offered.", "Only applies in windowed mode.",
		"V-Sync", "Off", "On", "Adaptive",
		"On removes tearing. Adaptive tears rather than halving the frame rate when a frame is missed.",
		"Frame rate cap", "unlimited",
		"Caps the whole main loop. Useful on a laptop — this game does not need 240 frames a second.",
		"Interface scale", "Magnifies the whole interface, spacing included. For text alone, see INTERFACE.",
		# settings — audio
		"Master volume", "Everything, at once.",
		"Sound effects", "Cards, coins, the sitter arriving and leaving.",
		"Interface sounds",
		"The click as focus moves and as a button is pressed. Playing on the keyboard, this is the sound you hear most.",
		"Mute", "Silence everything.",
		"Every sound in the game is a placeholder for now, and there is no music yet — which is why there is no music slider. See docs/SOUND_GUIDE.md.",
		# settings — interface
		"Animation speed", "off",
		"How fast cards deal, bars fill and values pulse. Set to 0 for no motion at all — the game jumps straight to each end state.",
		"Text size", "Makes the words bigger without magnifying the layout around them. Cards grow to match.",
		"High contrast",
		"A black ground, white text, and stronger secondary text. The game's usual dim greys are a deliberate look and hard to read for some people.",
		# settings — content
		"Load example mods",
		"Loads the bundled demo mod in mods_example/. Your own mods in the user mods folder always load.",
		"No content errors.", "Mods loaded: %s pack(s). %s",
		"Individual packs are switched on and off in MODS, where each one's name, order and load messages are.",
		# settings — controls
		"DEFAULT", "press a key…",
		"The whole game is playable from the keyboard or a gamepad: Tab and the arrow keys move between things, and Confirm activates whatever is highlighted.",
		"The gamepad button on the right is shown, not editable: only the keyboard key is rebindable, so changing one never costs you a controller button.",
		"Confirm / play a card", "Back / close", "Read it", "Show your deck", "Show your marks",
		# unlocks (sign-select)
		"LOCKED —", "Finish a run as %s", "Reach %s of %s", "Finish two runs",
		"Language",
		"%d%% translated (%d of %d strings). Anything untranslated falls back to English.",
		"BACK",
		# library
		"All pools", "All elements", "Search by name…",
		"Basics", "Chromatic", "Minor", "Arcana",
		"Pick a card on the left to edit it.", "Nothing matches those filters.",
		"READS AS", "CORE", "EFFECTS", "FLAGS",
		"Energy cost", "Base restore", "Element", "None",
		"REVERT THIS CARD", "REVERT ALL CARDS",
		"Set a value to 0 to remove that effect from the card entirely.",
		"The usual amount for this effect.",
		# run screens
		"CHOOSE YOUR SIGN", "Every reader is a sign, an element, and a starting deck of ten.",
		"Starts with:", "Who knocks tonight?", "NIGHT", "KNOCK",
		"YOUR HAND — hover a card for its full text", "SAID SO FAR", "(nothing yet)",
		"READ IT", "Composure", "Energy", "Reading", "Denial wall", "Discarded:",
		"BEGIN AGAIN", "sign", "cost", "composure", "denial", "readings",
		"THE APOTHECARY", "ELITE", "THE MAYOR", "ONCE", "PIERCE", "No element",
		# run header + overlays
		"Faith", "Centimes", "Mended", "DECK", "MARKS", "CLOSE",
		"YOUR DECK", "YOUR HANDS", "cards",
		"Nothing on your hands yet. Rings and marks come from elites, events and the apothecary.",
		# result / end-of-run (keys emitted by Run.gd — see its header)
		"GOES HOME WHOLE", "PUTS THE COAT BACK ON", "TAKE SOMETHING FOR IT",
		"SEE WHAT THEY SAY", "%s is whole enough", "%s leaves as they came, only later",
		"Composure at the end", "Readings used", "Faith earned", "Faith kept",
		"(%s of it overflow)", "Off a hard one", "it stays on your hands",
		"the money was on the table", "And that is the whole of it", "one is all it takes",
		"ONE OF THEM WENT HOME AS THEY CAME", "THREE NIGHTS, AND THE KNOCKING STOPS",
		"Restored", "Deck", "Centimes left", "SKIP", "%s cards",
		# library extras
		"CHANGED", "● marks a card you've changed", "from %s",
		"Pierces denial", "Once per sitter", "Restores faith, not composure",
		"Counts as every element", "Reads as their element",
		"Counts as your current element", "No element (basic decency)",
		# keyword glossary (UIKit.KEYS)
		"ONCE — it can be said one time a sitter, then it is spoken for good.",
		"ENERGY — what a single reading can pay for. It comes back in full every reading.",
		"DRAW — take that many more cards into your hand, straight away.",
		"DISCARD — every reading, whatever is left in your hand goes. You draw a fresh one.",
		"DENIAL — their sign. One named thing it does to every reading you give them.",
		"COMPOSURE — what you are filling. Fill it before they leave and they go home whole.",
		"FAITH — your score, and what the village says about you afterwards.",
		"CENTIMES — money. It buys cards and ink from the apothecary.",
		"FOLLOWS — it only pays if the card said before it carried that sign.",
		"FIRST — it only pays if it opens the sentence.",
		"LAST — it only pays if it closes the sentence.",
	]


func _load_existing(path: String) -> Dictionary:
	if not FileAccess.file_exists(path):
		return {}
	var f := FileAccess.open(path, FileAccess.READ)
	var parsed = JSON.parse_string(f.get_as_text())
	f.close()
	return parsed if typeof(parsed) == TYPE_DICTIONARY else {}
