## Dev tool: (re)generates data/base/art_manifest.json from live Content, so
## the artist's checklist can never drift out of sync with what the game
## actually contains. Run after adding/renaming/removing any card, reader, or
## sitter:
##   godot --headless --path godot -s tests/gen_art_manifest.gd
##
## Existing entries are PRESERVED (status, notes, and any hand-edited fields
## survive a regen) — this only adds newly-discovered assets and reports what
## disappeared, rather than clobbering work in progress.
extends SceneTree

const OUT_PATH := "res://data/base/art_manifest.json"


func _initialize() -> void:
	var content: Node = root.get_node("Content")
	await process_frame
	content.reload()

	var existing := _load_existing()
	var assets := {}
	var added: Array[String] = []

	var add = func(id: String, kind: String, display: String, extra: Dictionary):
		if existing.has(id):
			assets[id] = existing[id]
			# Keep the artist's own fields, but refresh the derived ones so a
			# renamed sitter/retyped element shows up correctly in the guide.
			assets[id]["kind"] = kind
			assets[id]["display"] = display
			for k in extra:
				assets[id][k] = extra[k]
			return
		var rec := {"kind": kind, "display": display, "status": "missing", "file": "", "notes": ""}
		for k in extra:
			rec[k] = extra[k]
		assets[id] = rec
		added.append(id)

	for pool_name in ["cards_basics", "cards_chroma", "cards_minor", "cards_arcana"]:
		for c in content.registries.get(pool_name, []):
			var el = c.get("el")
			add.call(
				"card/" + _slug(c["n"]), "card", c["n"],
				{
					"pool": pool_name,
					"element": el if el != null else "none",
					"rarity": c.get("r", ""),
					"archetype": c.get("a", ""),
					"spoken": c.get("sp", ""),
					"flavor": c.get("fl", ""),
				}
			)

	for r in content.readers:
		add.call(
			"reader/" + _slug(r["k"]), "reader", "%s — %s" % [r["name"], r["sign"]],
			{"element": r["el"], "planet": r.get("planet", ""), "flavor": r.get("line", "")}
		)

	for s in content.sitters:
		add.call(
			"sitter/" + _slug(s["name"]), "sitter", "%s · %s" % [s["name"], s["role"]],
			{"element": s["el"], "pronoun": s.get("p", "they"), "flavor": s.get("brings", "")}
		)
	var boss: Dictionary = content.boss
	if not boss.is_empty():
		add.call(
			"sitter/" + _slug(boss["name"]), "sitter", "%s · %s" % [boss["name"], boss["role"]],
			{"element": boss["el"], "pronoun": boss.get("p", "they"), "flavor": boss.get("brings", ""), "boss": true}
		)

	var removed: Array = existing.keys().filter(func(k): return not assets.has(k))

	var doc := {
		"_comment": "GENERATED by tests/gen_art_manifest.gd from live Content — re-run it after adding or renaming any card/reader/sitter rather than hand-adding rows. Hand-edited fields (status, file, notes) on existing entries are preserved across regens. See docs/ART_GUIDE.md for what each field means and the spec every image must meet.",
		"spec": _spec(),
		"assets": assets,
	}

	var f := FileAccess.open(OUT_PATH, FileAccess.WRITE)
	f.store_string(JSON.stringify(doc, "  ") + "\n")
	f.close()

	var by_status := {}
	for id in assets:
		var st: String = assets[id].get("status", "missing")
		by_status[st] = int(by_status.get(st, 0)) + 1
	print("wrote %s — %d assets (%d cards, %d readers, %d sitters)" % [
		OUT_PATH, assets.size(),
		assets.keys().filter(func(k): return k.begins_with("card/")).size(),
		assets.keys().filter(func(k): return k.begins_with("reader/")).size(),
		assets.keys().filter(func(k): return k.begins_with("sitter/")).size(),
	])
	print("  by status: ", by_status)
	if not added.is_empty():
		print("  added %d new: %s" % [added.size(), ", ".join(added.slice(0, 8)) + ("…" if added.size() > 8 else "")])
	if not removed.is_empty():
		printerr("  WARNING: %d entries no longer exist in Content and were dropped: %s" % [removed.size(), ", ".join(removed)])
	quit(0)


func _spec() -> Dictionary:
	return {
		"card_art": {
			"pixels": "512x512", "aspect": "1:1 square",
			"format": "PNG, RGBA, transparent background allowed",
			"safe_zone": "Keep the focal subject inside the centre 440x440. The card frame overlays ~36px on every edge, and the top ~52px carries the cost/restore numbers.",
			"notes": "Displayed at roughly 106x106 in the hand at 1x, so it must still read at thumbnail size. 512 gives headroom for a zoomed card-inspect view later.",
		},
		"portrait_art": {
			"pixels": "768x1024", "aspect": "3:4 portrait",
			"format": "PNG, RGBA",
			"safe_zone": "Face and shoulders inside the top 768x768. The bottom quarter can be cropped or covered by the name plate at some sizes.",
			"notes": "Used for sitters (the villager across the table) and readers (your own fortune-teller on the sign-select screen).",
		},
		"naming": "<kind>/<slug>.png under assets/art/ — e.g. assets/art/card/pour-the-tea.png, assets/art/sitter/mme-perrot.png. The slug is the asset id after the kind prefix; use it exactly as written in this file.",
		"status_values": ["missing", "wip", "final"],
	}


## Lowercase, ASCII-folded, hyphen-separated. Deliberately strips accents
## (Thérèse -> therese, Père Renaud -> pere-renaud) so filenames stay
## portable across filesystems and safe in git/Workshop archives.
func _slug(s: String) -> String:
	var out := s.to_lower()
	var from := ["é", "è", "ê", "ë", "à", "â", "ä", "î", "ï", "ô", "ö", "ù", "û", "ü", "ç", "’", "'"]
	var to := ["e", "e", "e", "e", "a", "a", "a", "i", "i", "o", "o", "u", "u", "u", "c", "", ""]
	for i in from.size():
		out = out.replace(from[i], to[i])
	var result := ""
	for ch in out:
		if (ch >= "a" and ch <= "z") or (ch >= "0" and ch <= "9"):
			result += ch
		elif result.length() > 0 and not result.ends_with("-"):
			result += "-"
	return result.trim_suffix("-")


func _load_existing() -> Dictionary:
	if not FileAccess.file_exists(OUT_PATH):
		return {}
	var f := FileAccess.open(OUT_PATH, FileAccess.READ)
	var parsed = JSON.parse_string(f.get_as_text())
	f.close()
	if typeof(parsed) != TYPE_DICTIONARY:
		return {}
	return parsed.get("assets", {})
