## Headless test for the art pipeline (manifest -> Art.gd -> texture or null).
##   godot --headless --path godot -s tests/test_art.gd
##
## The contract this pins down is the one the whole "art arrives piece by
## piece" workflow rests on: a delivered asset resolves to a real Texture2D,
## and everything else resolves to null WITHOUT erroring, so every UI caller
## can fall back to its placeholder. If this passes, the game is safe to run
## at any point between zero art and complete art.
extends SceneTree

var failures: Array[String] = []
var content: Node
var art: Node


func _initialize() -> void:
	content = root.get_node("Content")
	art = root.get_node("Art")
	await process_frame
	content.reload()
	art.reload()

	_test_manifest_loaded()
	_test_slug_matches_generator()
	_test_missing_art_is_null_not_error()
	_test_delivered_art_loads()
	_test_every_manifest_id_is_resolvable()

	if failures.is_empty():
		print("ALL PASS — art status: ", art.status_summary())
		quit(0)
	else:
		for f in failures:
			printerr("FAIL: ", f)
		quit(1)


func check(cond: bool, label: String) -> void:
	if not cond:
		failures.append(label)


func _test_manifest_loaded() -> void:
	check(not art.manifest.is_empty(), "art manifest should load")
	check(art.spec.has("card_art"), "manifest should carry the card_art spec")
	check(art.spec.has("portrait_art"), "manifest should carry the portrait_art spec")


## Art.slug() and gen_art_manifest.gd's _slug() are separate copies of the
## same rule (one runs in-game, one is a dev tool). If they ever drift, ids
## generated by the tool stop resolving at runtime and every asset silently
## falls back to placeholder — so pin the tricky cases down here.
func _test_slug_matches_generator() -> void:
	check(art.slug("Pour The Tea") == "pour-the-tea", "basic slug, got %s" % art.slug("Pour The Tea"))
	check(art.slug("Thérèse") == "therese", "accented slug, got %s" % art.slug("Thérèse"))
	check(art.slug("Père Renaud") == "pere-renaud", "accented two-word slug, got %s" % art.slug("Père Renaud"))
	check(art.slug("Stand Up Mid-Sentence") == "stand-up-mid-sentence", "hyphenated slug, got %s" % art.slug("Stand Up Mid-Sentence"))
	check(art.slug("The Widow's Wedding Band") == "the-widows-wedding-band", "apostrophe slug, got %s" % art.slug("The Widow's Wedding Band"))


func _test_missing_art_is_null_not_error() -> void:
	var undelivered: Dictionary = content.get_card("Ask Them Why")
	check(not undelivered.is_empty(), "Ask Them Why should exist in content")
	check(art.card_texture(undelivered) == null, "an undelivered card should resolve to null, not a texture")
	check(art.texture("card/does-not-exist-at-all") == null, "an id absent from the manifest should resolve to null")


## Depends on tests/gen_test_art.gd having been run (it writes two gradient
## placeholders and flips their status to "final"). Skips itself rather than
## failing if that hasn't happened or the temp files were cleaned up, since
## the real art landing later must not break this test either.
func _test_delivered_art_loads() -> void:
	var entry: Dictionary = art.manifest.get("card/pour-the-tea", {})
	if entry.get("status", "missing") == "missing":
		print("  (skipping delivered-art check: card/pour-the-tea is still 'missing')")
		return
	var tea: Dictionary = content.get_card("Pour The Tea")
	var tex = art.card_texture(tea)
	check(tex != null, "card/pour-the-tea is marked '%s' so it should load a texture" % entry.get("status"))
	if tex != null:
		check(tex.get_width() > 0 and tex.get_height() > 0, "loaded texture should have real dimensions")

	var perrot: Dictionary = content.get_sitter("Mme Perrot")
	if art.manifest.get("sitter/mme-perrot", {}).get("status", "missing") != "missing":
		check(art.sitter_texture(perrot) != null, "sitter/mme-perrot is marked delivered so it should load")


## Every id the manifest lists must be resolvable without throwing, whatever
## its status — this is the "the game runs at any point during production"
## guarantee, checked across all 80-odd assets rather than a sample.
func _test_every_manifest_id_is_resolvable() -> void:
	var checked := 0
	for id in art.manifest:
		art.texture(id)  # must not error; null is a fine answer
		checked += 1
	check(checked > 50, "expected to sweep the whole manifest, only saw %d" % checked)

	# And the ids the game derives at runtime must match manifest ids, or
	# nothing would ever resolve even once art exists.
	for c in content.cards_minor:
		check(art.manifest.has(art.card_id(c)), "manifest missing id for card %s (%s)" % [c["n"], art.card_id(c)])
	for s in content.sitters:
		check(art.manifest.has(art.sitter_id(s)), "manifest missing id for sitter %s" % s["name"])
	for r in content.readers:
		check(art.manifest.has(art.reader_id(r)), "manifest missing id for reader %s" % r["k"])
