## Headless test for the art pipeline (manifest -> Art.gd -> texture or null).
##   godot --headless --path godot -s tests/test_art.gd
##
## The contract this pins down is the one the whole "art arrives piece by
## piece" workflow rests on: a delivered asset resolves to a real Texture2D,
## and everything else resolves to null WITHOUT erroring, so every UI caller
## can fall back to its placeholder. If this passes, the game is safe to run
## at any point between zero art and complete art.
extends SceneTree

var failures: Array[String] = []
var content: Node
var art: Node


func _initialize() -> void:
	content = root.get_node("Content")
	art = root.get_node("Art")
	await process_frame
	content.reload()
	art.reload()

	_test_manifest_loaded()
	_test_slug_matches_generator()
	_test_missing_art_is_null_not_error()
	_test_delivered_art_loads()
	_test_every_manifest_id_is_resolvable()
	_test_unimported_file_loads()
	await _test_the_card_holds_a_window_open()
	_test_the_guide_states_the_window_it_gets()

	if failures.is_empty():
		print("ALL PASS — art status: ", art.status_summary())
		quit(0)
	else:
		for f in failures:
			printerr("FAIL: ", f)
		quit(1)


func check(cond: bool, label: String) -> void:
	if not cond:
		failures.append(label)


func _test_manifest_loaded() -> void:
	check(not art.manifest.is_empty(), "art manifest should load")
	check(art.spec.has("card_art"), "manifest should carry the card_art spec")
	check(art.spec.has("portrait_art"), "manifest should carry the portrait_art spec")


## Art.slug() and gen_art_manifest.gd's _slug() are separate copies of the
## same rule (one runs in-game, one is a dev tool). If they ever drift, ids
## generated by the tool stop resolving at runtime and every asset silently
## falls back to placeholder — so pin the tricky cases down here.
func _test_slug_matches_generator() -> void:
	check(art.slug("Pour The Tea") == "pour-the-tea", "basic slug, got %s" % art.slug("Pour The Tea"))
	check(art.slug("Thérèse") == "therese", "accented slug, got %s" % art.slug("Thérèse"))
	check(art.slug("Père Renaud") == "pere-renaud", "accented two-word slug, got %s" % art.slug("Père Renaud"))
	check(art.slug("Stand Up Mid-Sentence") == "stand-up-mid-sentence", "hyphenated slug, got %s" % art.slug("Stand Up Mid-Sentence"))
	check(art.slug("The Widow's Wedding Band") == "the-widows-wedding-band", "apostrophe slug, got %s" % art.slug("The Widow's Wedding Band"))


func _test_missing_art_is_null_not_error() -> void:
	var undelivered: Dictionary = content.get_card("Ask Them Why")
	check(not undelivered.is_empty(), "Ask Them Why should exist in content")
	check(art.card_texture(undelivered) == null, "an undelivered card should resolve to null, not a texture")
	check(art.texture("card/does-not-exist-at-all") == null, "an id absent from the manifest should resolve to null")


## Depends on tests/gen_test_art.gd having been run (it writes two gradient
## placeholders and flips their status to "final"). Skips itself rather than
## failing if that hasn't happened or the temp files were cleaned up, since
## the real art landing later must not break this test either.
func _test_delivered_art_loads() -> void:
	var entry: Dictionary = art.manifest.get("card/pour-the-tea", {})
	if entry.get("status", "missing") == "missing":
		print("  (skipping delivered-art check: card/pour-the-tea is still 'missing')")
		return
	var tea: Dictionary = content.get_card("Pour The Tea")
	var tex = art.card_texture(tea)
	check(tex != null, "card/pour-the-tea is marked '%s' so it should load a texture" % entry.get("status"))
	if tex != null:
		check(tex.get_width() > 0 and tex.get_height() > 0, "loaded texture should have real dimensions")

	var perrot: Dictionary = content.get_sitter("Mme Perrot")
	if art.manifest.get("sitter/mme-perrot", {}).get("status", "missing") != "missing":
		check(art.sitter_texture(perrot) != null, "sitter/mme-perrot is marked delivered so it should load")


## The loader has to read a file the editor has never imported.
##
## This is the case that actually matters and the one nothing was covering:
## art delivered after the fact and dropped into assets/art/, or shipped by a
## mod in user://mods/, has no .import file and no converted resource under
## .godot/imported/ — and a mod's never can, since the import pipeline only
## covers res:// assets known at export time. Art.gd used ResourceLoader.exists()
## + load(), which works for exactly the art that has been through the editor
## and nothing else. The delivered-art check above cannot catch that, because
## it skips entirely while every asset is still "missing" — which is always,
## until the artist delivers.
##
## Writes its own file to user:// and cleans up, so it needs no committed art.
func _test_unimported_file_loads() -> void:
	var path := "user://_test_unimported.png"
	var img := Image.create(8, 8, false, Image.FORMAT_RGBA8)
	img.fill(Color(0.4, 0.2, 0.6))
	check(img.save_png(path) == OK, "could not write the test image")

	var tex = art._load_texture(path)
	check(tex != null, "a file the editor never imported must still load")
	if tex != null:
		check(tex.get_width() == 8 and tex.get_height() == 8,
			"loaded texture should be 8x8, got %dx%d" % [tex.get_width(), tex.get_height()])

	check(art._load_texture("user://_definitely_not_here.png") == null,
		"a missing file should be null, not an error")
	DirAccess.remove_absolute(path)


## Every id the manifest lists must be resolvable without throwing, whatever
## its status — this is the "the game runs at any point during production"
## guarantee, checked across all 80-odd assets rather than a sample.
func _test_every_manifest_id_is_resolvable() -> void:
	var checked := 0
	for id in art.manifest:
		art.texture(id)  # must not error; null is a fine answer
		checked += 1
	check(checked > 50, "expected to sweep the whole manifest, only saw %d" % checked)

	# And the ids the game derives at runtime must match manifest ids, or
	# nothing would ever resolve even once art exists.
	#
	# BASE CONTENT ONLY. This manifest belongs to the base pack, and every merged
	# record is stamped with the pack that defined it (ModLoader.PACK_FIELD) — so
	# a missing entry for a mod's record means "a mod added content", not "the
	# base game lost a card". Those are opposite conclusions from the same
	# symptom, and without the stamp this check could only ever reach the wrong
	# one. A mod that wants art ships its own manifest.
	for c in content.cards_minor:
		if _is_base(c):
			check(art.manifest.has(art.card_id(c)), "manifest missing id for card %s (%s)" % [c["n"], art.card_id(c)])
	for s in content.sitters:
		if _is_base(s):
			check(art.manifest.has(art.sitter_id(s)), "manifest missing id for sitter %s" % s["name"])
	for r in content.readers:
		if _is_base(r):
			check(art.manifest.has(art.reader_id(r)), "manifest missing id for reader %s" % r["k"])


## THE ART WINDOW IS HELD OPEN, AND NOTHING IS DRAWN OVER IT.
##
## Two promises made to whoever is drawing these, and both are the kind that
## rot quietly. Before this, a card with no art centred its name in the middle
## of the face and a card WITH art put that name back on top of it over a scrim
## — so the layout moved the day a drawing arrived, and then covered the bottom
## third of it. Either would be found by an artist, months later, in their own
## work.
func _test_the_card_holds_a_window_open() -> void:
	var UIKitScript = load("res://scenes/UIKit.gd")
	var card: Dictionary = content.get_card("Turn The Top Card")
	check(not card.is_empty(), "the deck should still have a Turn The Top Card to draw")
	if card.is_empty():
		return

	var face: Control = UIKitScript.card_face(card, Callable(), true, false)
	root.add_child(face)
	# The face is measured, not merely built: a minimum size is not a rect.
	face.size = UIKitScript.card_face_size()
	await process_frame
	await process_frame

	var well: Control = _find(face, "ArtWell")
	check(well != null, "every card face should hold an art window open, art or no art")
	if well != null:
		var window := Rect2(well.global_position, well.size)
		check(window.size.x > 1.0 and window.size.y > 1.0,
			"the art window should have a real size, got %s" % window.size)
		# Everything else on the card has to stay out of it.
		for node in _all_of(face, []):
			var c := node as Control
			if c == null or c == well or well.is_ancestor_of(c) or not c.is_visible_in_tree():
				continue
			if c.size.x <= 0.0 or c.size.y <= 0.0:
				continue
			var r := Rect2(c.global_position, c.size)
			# `wrap` and the vbox inside it contain the window rather than
			# covering it; anything that merely OVERLAPS is drawn across it.
			if c.is_ancestor_of(well):
				continue
			check(not r.intersects(window),
				"nothing may be drawn over the card's art window — %s (%s) overlaps it" % [c.name, r])
	face.queue_free()
	await process_frame


## The window's shape and the shape the guide asks an artist to draw must be the
## same shape. They are stated in two files that nothing else connects.
func _test_the_guide_states_the_window_it_gets() -> void:
	var UIKitScript = load("res://scenes/UIKit.gd")
	var want: float = UIKitScript.ART_WELL.y / UIKitScript.ART_WELL.x
	var text := FileAccess.get_file_as_string("res://docs/ART_GUIDE.md")
	check(text != "", "the art guide should be readable")
	var found := false
	# The first "W x H px" the card section states is the card art spec.
	var re := RegEx.new()
	re.compile("\\*\\*(\\d+)\\s*[x×]\\s*(\\d+)\\s*px\\*\\*")
	for m in re.search_all(text):
		var w := float(m.get_string(1))
		var h := float(m.get_string(2))
		if is_equal_approx(h / w, want):
			found = true
			break
	check(found, "docs/ART_GUIDE.md should ask for card art in the window's own %.2f:1 shape" % [1.0 / want])


func _find(node: Node, named: String) -> Control:
	for child in node.get_children():
		if child.name == named and child is Control:
			return child
		var deeper := _find(child, named)
		if deeper != null:
			return deeper
	return null


func _all_of(node: Node, out: Array) -> Array:
	for child in node.get_children():
		out.append(child)
		_all_of(child, out)
	return out


## A record with no pack stamp is treated as base, so this errs towards
## checking too much rather than towards silently checking nothing.
func _is_base(rec: Dictionary) -> bool:
	return str(rec.get("_pack", "parlour.base")) == "parlour.base"
