## Autoload. The merged, ready-to-query content registries — the base game
## plus every mod pack ModLoader found, already merged. Everything else in the
## game (Rules, Run, the UI) reads content through this singleton and never
## touches ModLoader or raw JSON directly.
extends Node

## Loaded by path rather than by its `class_name`.
##
## A `class_name` global is only declared once Godot has written
## .godot/global_script_class_cache.cfg, and that file is generated by the
## EDITOR and gitignored (it is a cache, not source). So on a fresh clone the
## identifier `ModLoader` does not exist, this script fails to compile, and
## every autoload that touches Content fails with it — which is to say the
## whole game, before anything has had a chance to report a useful error.
##
## The README tells people to run the headless tests, so "clone and run" is the
## first thing anyone does; it was broken and only worked here because this
## container had a cache left over from an earlier editor-less run. preload()
## resolves by path and needs no registry. This is the third time a bare global
## name has bitten this port — see Nav.gd's header for the other two.
const MOD_LOADER := preload("res://autoload/ModLoader.gd")

## NOTE: this used to be a `const LOAD_EXAMPLE_MODS := true` that nothing
## actually read — ModLoader scanned res://mods_example/ unconditionally, so
## the constant was documentation, not behaviour. It's now a real player
## setting that ModLoader genuinely honours (see reload()).

## Emitted at the end of every reload(). Art, Audio, I18n and Save each connect
## to it in their own _ready() and re-sync themselves.
##
## This used to be the CALLER's job: a screen that reloaded content also had to
## remember to call Art.reload(), Audio.reload(), I18n.reload() and to put the
## run in progress through Save so its copies of content records were looked up
## again. The Mods screen did all of it. The Library did two of the four — so
## editing a card while a run was in progress changed the registry and left the
## deck holding the old version, and the player watched their edit do nothing.
##
## Fanning out from here instead means the list cannot be got wrong once and
## then copied wrong forever: each subsystem owns its own response, and a new
## screen that reloads content gets all of it for free. Connection order is
## autoload order (see project.godot) — Art, Audio, I18n, then Save — which is
## the order that matters, since Save's re-resolution reads the registries and
## the locale that the first three have just refreshed.
signal reloaded

var registries: Dictionary = {}
var load_errors: Array[String] = []
## Every pack discovery found, in load order, loaded or not. See ModLoader.packs.
var packs: Array[Dictionary] = []

var elements: Dictionary
var ring: Array
var next_el: Dictionary
var opp_el: Dictionary
var neighbors: Dictionary
var fx: Dictionary
var denial_shield: Dictionary
var denial_wall: Dictionary
var pronouns: Dictionary
var sounds: Dictionary
var minitel_codes: Dictionary
var card_effects: Array
var signs: Array
var jobs: Dictionary
var readers: Array
var cards_basics: Array
var cards_chroma: Array
var cards_minor: Array
var cards_arcana: Array
var relics: Array
var marks: Array
var elite_twists: Array
var sitters: Array
var boss: Dictionary
var events: Array
var shop: Dictionary

# name -> card dict, across every pool, built once after load for O(1) lookup
# (readers reference their 2 starting cards by name, rewards resolve by name, etc).
var _cards_by_name: Dictionary = {}
var _card_effects_by_key: Dictionary = {}
var _signs_by_key: Dictionary = {}
var _readers_by_key: Dictionary = {}
var _sitters_by_name: Dictionary = {}


func _ready() -> void:
	reload()


func reload() -> void:
	var loader := MOD_LOADER.new()
	loader.load_example_mods = bool(Settings.get_value("load_example_mods"))
	loader.disabled_ids = Array(Settings.get_value("disabled_mods"))
	registries = loader.build_registries()
	load_errors = loader.errors
	packs = loader.packs
	for e in load_errors:
		push_warning("[Content] " + e)

	elements = registries.get("elements", {})
	ring = registries.get("ring", [])
	next_el = registries.get("next", {})
	opp_el = registries.get("opp", {})
	neighbors = registries.get("neighbors", {})
	fx = registries.get("fx", {})
	denial_shield = registries.get("denial_shield", {})
	denial_wall = registries.get("denial_wall", {})
	pronouns = registries.get("pronouns", {})
	sounds = registries.get("sounds", {})
	minitel_codes = registries.get("minitel_codes", {})
	card_effects = registries.get("card_effects", [])
	signs = registries.get("signs", [])
	jobs = registries.get("jobs", {})
	readers = registries.get("readers", [])
	cards_basics = registries.get("cards_basics", [])
	cards_chroma = registries.get("cards_chroma", [])
	cards_minor = registries.get("cards_minor", [])
	cards_arcana = registries.get("cards_arcana", [])
	relics = registries.get("relics", [])
	marks = registries.get("marks", [])
	elite_twists = registries.get("elite_twists", [])
	sitters = registries.get("sitters", [])
	boss = registries.get("boss", {})
	events = registries.get("events", [])
	shop = registries.get("shop", {})

	_index()
	reloaded.emit()


func _index() -> void:
	_cards_by_name.clear()
	for pool in [cards_basics, cards_chroma, cards_minor, cards_arcana]:
		for c in pool:
			_cards_by_name[c["n"]] = c
	_card_effects_by_key.clear()
	for e in card_effects:
		_card_effects_by_key[e["k"]] = e
	_signs_by_key.clear()
	for s in signs:
		_signs_by_key[s["k"]] = s
	_readers_by_key.clear()
	for r in readers:
		_readers_by_key[r["k"]] = r
	_sitters_by_name.clear()
	for s in sitters:
		_sitters_by_name[s["name"]] = s


func get_card(card_name: String) -> Dictionary:
	return _cards_by_name.get(card_name, {})


func has_card(card_name: String) -> bool:
	return _cards_by_name.has(card_name)


func get_card_effect(key: String) -> Dictionary:
	return _card_effects_by_key.get(key, {})


func get_sign(key: String) -> Dictionary:
	return _signs_by_key.get(key, {})


func get_reader(key: String) -> Dictionary:
	return _readers_by_key.get(key, {})


func get_sitter(sitter_name: String) -> Dictionary:
	return _sitters_by_name.get(sitter_name, {})


func get_job(role: String) -> Dictionary:
	return jobs.get(role, {"t": "", "fx": ""})


func get_fx(key: String) -> Dictionary:
	return fx.get(key, {})
