## Autoload. The one place the game's version is written down, and the credits
## that go with it.
##
## Neither existed. A player could not tell one build from another — which
## matters the first time somebody reports a bug and cannot say which version
## they were playing — and nothing in the game said where it came from, which
## for a port of somebody else's prototype is not a detail to leave out.
##
## WHY AN AUTOLOAD AND NOT A CONSTANT IN A SCENE. Three places need the version
## (the main menu, the credits screen, and the base pack's mod.json, which
## declares the version of the content), and a number written down three times
## is a number that is wrong in two of them within a month.
## tests/test_dead_content.gd asserts this and data/base/mod.json agree.
extends Node

## Semantic-ish. MINOR moves when the game changes for the player; PATCH when
## something is fixed without changing what the game is. It is 0.x because the
## content is not finished — see docs/PORTING_NOTES.md for what is missing.
const MAJOR := 0
const MINOR := 2
const PATCH := 0


func string() -> String:
	return "%d.%d.%d" % [MAJOR, MINOR, PATCH]


## Version plus the engine it is running on, for a bug report. Godot's own
## version is read at runtime rather than written here, so it cannot be stale.
func full() -> String:
	var e := Engine.get_version_info()
	return "%s · Godot %s.%s.%s" % [string(), e.get("major", "?"), e.get("minor", "?"), e.get("patch", 0)]


## The credits, as [heading, [lines]] pairs — the same shape HowToPlay uses, so
## one renderer does both.
##
## EVERYTHING HERE IS A FACT ABOUT THE REPOSITORY, not a guess. No names are
## invented: the prototype is credited as a file, the engine and the bundled
## font by what they are. Where a person's name belongs, there is a line saying
## so and nothing else — an empty slot is honest, a placeholder name is not.
func credits() -> Array:
	return [
		[I18n.t("THE GAME"), [
			I18n.t("Parlour began as a self-contained browser prototype, Parlour v23.dc.html — the design, the writing, the cards and the numbers are all its author's."),
			I18n.t("This is a port of that prototype to Godot. The rules engine is a direct translation of its simulate(); where the two disagree, the prototype is right."),
			I18n.t("Design and writing: see the repository."),
		]],
		[I18n.t("BUILT WITH"), [
			"· " + I18n.t("Godot Engine %s — MIT licence, godotengine.org") % _godot_version(),
			"· " + I18n.t("The engine's default interface font, Open Sans (Apache 2.0)."),
		]],
		[I18n.t("ART AND SOUND"), [
			I18n.t("Every card face, portrait and sound in this build is a placeholder generated by the project itself, and is meant to be replaced. See docs/ART_GUIDE.md and docs/SOUND_GUIDE.md."),
			I18n.t("Illustration: unfilled."),
			I18n.t("Music and sound: unfilled."),
		]],
		[I18n.t("TRANSLATION"), _translation_lines()],
		[I18n.t("THIS BUILD"), [
			"· " + I18n.t("Version %s") % string(),
			"· " + I18n.t("Engine %s") % _godot_version(),
			"· " + I18n.t("Content packs loaded: %s") % _pack_names(),
		]],
	]


func _godot_version() -> String:
	var e := Engine.get_version_info()
	return "%s.%s.%s" % [e.get("major", "?"), e.get("minor", "?"), e.get("patch", 0)]


## Credits every locale that ships, by name, and says plainly how far each one
## has got — a half-finished translation is worth crediting and worth being
## honest about.
func _translation_lines() -> Array:
	var out: Array = []
	for code in I18n.LOCALES:
		if code == "en":
			continue
		var cov: Dictionary = I18n.coverage(str(code))
		var total := int(cov.get("total", 0))
		var done := int(cov.get("translated", 0))
		var pct := 0 if total == 0 else int(round(100.0 * done / total))
		out.append("· %s — %d%%" % [I18n.LOCALES[code], pct])
	if out.is_empty():
		out.append(I18n.t("English only."))
	out.append(I18n.t("Translators: unfilled. See docs/LOCALIZATION.md."))
	return out


## Every pack that actually loaded, named. Puts a modded build's provenance in
## the credits, which is where someone filing a bug will be asked to look.
func _pack_names() -> String:
	var names: Array = []
	for p in Content.packs:
		if bool(p.get("enabled", true)):
			names.append("%s %s" % [p.get("name", p.get("id", "?")), p.get("version", "")])
	return ", ".join(names) if not names.is_empty() else "—"
